planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/moveit_cpp/planning_scene_monitor"
  publish_planning_scene_topic: "/moveit_cpp/publish_planning_scene"
  monitored_planning_scene_topic: "/moveit_cpp/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

# 1. ABILITIAMO SIA OMPL CHE PILZ NELLE PIPELINE
planning_pipelines:
  pipeline_names: ["ompl", "pilz_industrial_motion_planner"]

# --- PARAMETRI DI GESTIONE TRAIETTORIA ED ESECUZIONE ---
trajectory_execution:
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.0
  trajectory_duration_monitoring: true

moveit_managed_controllers:
  - myco_arm_controller

controller_names:
  - myco_arm_controller

myco_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - myco_joint1
    - myco_joint2
    - myco_joint3
    - myco_joint4
    - myco_joint5
    - myco_joint6

# --- CONFIGURAZIONE SPECIFICA DI PILZ ---
pilz_industrial_motion_planner:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: "PTP"
    max_velocity_scaling_factor: 0.8       # Alziamo un po' la velocità (80%)
    max_acceleration_scaling_factor: 0.8   # Alziamo l'accelerazione (80%)

# --- PARAMETRI DI PIANIFICAZIONE DI DEFAULT PER IL BRACCIO ---
# Impostiamo Pilz PTP come preferito per avere movimenti fluidi e istantanei
myco_arm:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: "PTP" 
    planning_time: 0.1                     # Pilz calcola in meno di 100ms, non gli servono 3 secondi!
    max_velocity_scaling_factor: 0.8
    max_acceleration_scaling_factor: 0.8